export { default as LandingPage } from './LandingPage'
export { default as HeroSection } from './HeroSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as StatsSection } from './StatsSection'
export { default as HowItWorksSection } from './HowItWorksSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as FAQSection } from './FAQSection'